spring.application.name=serenemind-api


# DATABASE
spring.datasource.url=jdbc:mysql://mysql-36e4b5dd-sints2001-5cd6.l.aivencloud.com:22939/serenemind?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_9ieLSAKW9TugPMLys-2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



#debug=true
spring.jpa.hibernate.ddl-auto=update
debug=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Jwt
app.jwt.secret=9a4f2c8d3e1b7f6a5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f
app.jwt.expiration-ms=3600000

spring.jpa.open-in-view=false
server.address=0.0.0.0

app.jwt.refresh-expiration-ms=86400000

cloudinary.cloud-name=kvlzn4zk
cloudinary.api-key=977879591449957
cloudinary.api-secret=pz5K5fpH_gArDJgP-4Z3UW3daGk

# ── Multipart file upload limits ────────────────────────────────────
spring.servlet.multipart.max-request-size=50MB
cloudinary.journal-photo-folder=serenemind/journal-photos

spring.servlet.multipart.max-file-size=50MB


#AI api keys
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile

# Database Query Performance Profiling
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# Groq API Configuration (OpenAI Compatible)

server.port=8080


# Groq API Configuration (OpenAI Compatible)
#spring.ai.openai.api-key=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
#spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
#spring.ai.openai.chat.options.temperature=0.7

# Groq API Configuration (OpenAI Compatible)
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.chat.model=llama-3.3-70b-versatile
spring.ai.openai.chat.temperature=0.7

#spring.ai.openai.chat.options.response-format.type=JSON_OBJECT



